import { BsFacebook, BsInstagram, BsLinkedin, BsTwitter } from 'react-icons/bs';

export const timeZones = [
      { value: 'Etc/GMT+12', label: '(GMT -12:00) International Date Line West' },
      { value: 'Pacific/Pago_Pago', label: '(GMT -11:00) Midway Island, Samoa' },
      { value: 'Pacific/Honolulu', label: '(GMT -10:00) Hawaii' },
      { value: 'America/Anchorage', label: '(GMT -09:00) Alaska' },
      { value: 'America/Los_Angeles', label: '(GMT -08:00) Pacific Time (US & Canada)' },
      { value: 'America/Denver', label: '(GMT -07:00) Mountain Time (US & Canada)' },
      { value: 'America/Chicago', label: '(GMT -06:00) Central Time (US & Canada), Mexico City' },
      { value: 'America/New_York', label: '(GMT -05:00) Eastern Time (US & Canada), Bogota, Lima' },
      { value: 'America/Halifax', label: '(GMT -04:00) Atlantic Time (Canada), Caracas, La Paz' },
      { value: 'America/St_Johns', label: '(GMT -03:30) Newfoundland' },
      { value: 'America/Argentina/Buenos_Aires', label: '(GMT -03:00) Brazil, Buenos Aires, Georgetown' },
      { value: 'Atlantic/South_Georgia', label: '(GMT -02:00) Mid-Atlantic' },
      { value: 'Atlantic/Azores', label: '(GMT -01:00) Azores, Cape Verde Islands' },
      { value: 'Europe/London', label: '(GMT +00:00) Western Europe Time, London, Lisbon, Casablanca' },
      { value: 'Europe/Paris', label: '(GMT +01:00) Central Europe Time, Brussels, Copenhagen, Madrid, Paris' },
      { value: 'Europe/Athens', label: '(GMT +02:00) Eastern Europe Time, Cairo, Athens, Jerusalem' },
      { value: 'Europe/Moscow', label: '(GMT +03:00) Baghdad, Riyadh, Moscow, St. Petersburg' },
      { value: 'Asia/Tehran', label: '(GMT +03:30) Tehran' },
      { value: 'Asia/Dubai', label: '(GMT +04:00) Abu Dhabi, Muscat, Baku, Tbilisi' },
      { value: 'Asia/Kabul', label: '(GMT +04:30) Kabul' },
      { value: 'Asia/Karachi', label: '(GMT +05:00) Islamabad, Karachi, Tashkent' },
      { value: 'Asia/Kolkata', label: '(GMT +05:30) Chennai, Kolkata, Mumbai, New Delhi' },
      { value: 'Asia/Kathmandu', label: '(GMT +05:45) Kathmandu' },
      { value: 'Asia/Dhaka', label: '(GMT +06:00) Astana, Dhaka' },
      { value: 'Asia/Yangon', label: '(GMT +06:30) Yangon (Rangoon)' },
      { value: 'Asia/Bangkok', label: '(GMT +07:00) Bangkok, Hanoi, Jakarta' },
      { value: 'Asia/Shanghai', label: '(GMT +08:00) Beijing, Perth, Singapore, Hong Kong' },
      { value: 'Asia/Tokyo', label: '(GMT +09:00) Tokyo, Seoul, Osaka, Sapporo, Yakutsk' },
      { value: 'Australia/Darwin', label: '(GMT +09:30) Adelaide, Darwin' },
      { value: 'Australia/Sydney', label: '(GMT +10:00) Eastern Australia, Guam, Vladivostok' },
      { value: 'Pacific/Guadalcanal', label: '(GMT +11:00) Magadan, Solomon Islands, New Caledonia' },
      { value: 'Pacific/Auckland', label: '(GMT +12:00) Auckland, Wellington, Fiji, Kamchatka' },
      { value: 'Pacific/Tongatapu', label: "(GMT +13:00) Nuku'alofa" },
];

export const countries = [
      { label: 'Afghanistan', value: 'afghanistan' },
      { label: 'Albania', value: 'albania' },
      { label: 'Algeria', value: 'algeria' },
      { label: 'Andorra', value: 'andorra' },
      { label: 'Angola', value: 'angola' },
      { label: 'Antigua and Barbuda', value: 'antigua_and_barbuda' },
      { label: 'Argentina', value: 'argentina' },
      { label: 'Armenia', value: 'armenia' },
      { label: 'Australia', value: 'australia' },
      { label: 'Austria', value: 'austria' },
      { label: 'Azerbaijan', value: 'azerbaijan' },
      { label: 'Bahamas', value: 'bahamas' },
      { label: 'Bahrain', value: 'bahrain' },
      { label: 'Bangladesh', value: 'bangladesh' },
      { label: 'Barbados', value: 'barbados' },
      { label: 'Belarus', value: 'belarus' },
      { label: 'Belgium', value: 'belgium' },
      { label: 'Belize', value: 'belize' },
      { label: 'Benin', value: 'benin' },
      { label: 'Bhutan', value: 'bhutan' },
      { label: 'Bolivia', value: 'bolivia' },
      { label: 'Bosnia and Herzegovina', value: 'bosnia_and_herzegovina' },
      { label: 'Botswana', value: 'botswana' },
      { label: 'Brazil', value: 'brazil' },
      { label: 'Brunei', value: 'brunei' },
      { label: 'Bulgaria', value: 'bulgaria' },
      { label: 'Burkina Faso', value: 'burkina_faso' },
      { label: 'Burundi', value: 'burundi' },
      { label: 'Cabo Verde', value: 'cabo_verde' },
      { label: 'Cambodia', value: 'cambodia' },
      { label: 'Cameroon', value: 'cameroon' },
      { label: 'Canada', value: 'canada' },
      { label: 'Central African Republic', value: 'central_african_republic' },
      { label: 'Chad', value: 'chad' },
      { label: 'Chile', value: 'chile' },
      { label: 'China', value: 'china' },
      { label: 'Colombia', value: 'colombia' },
      { label: 'Comoros', value: 'comoros' },
      { label: 'Congo (Congo-Brazzaville)', value: 'congo' },
      { label: 'Costa Rica', value: 'costa_rica' },
      { label: 'Croatia', value: 'croatia' },
      { label: 'Cuba', value: 'cuba' },
      { label: 'Cyprus', value: 'cyprus' },
      { label: 'Czechia (Czech Republic)', value: 'czechia' },
      { label: 'Denmark', value: 'denmark' },
      { label: 'Djibouti', value: 'djibouti' },
      { label: 'Dominica', value: 'dominica' },
      { label: 'Dominican Republic', value: 'dominican_republic' },
      { label: 'Ecuador', value: 'ecuador' },
      { label: 'Egypt', value: 'egypt' },
      { label: 'El Salvador', value: 'el_salvador' },
      { label: 'Equatorial Guinea', value: 'equatorial_guinea' },
      { label: 'Eritrea', value: 'eritrea' },
      { label: 'Estonia', value: 'estonia' },
      { label: 'Eswatini (fmr. Swaziland)', value: 'eswatini' },
      { label: 'Ethiopia', value: 'ethiopia' },
      { label: 'Fiji', value: 'fiji' },
      { label: 'Finland', value: 'finland' },
      { label: 'France', value: 'france' },
      { label: 'Gabon', value: 'gabon' },
      { label: 'Gambia', value: 'gambia' },
      { label: 'Georgia', value: 'georgia' },
      { label: 'Germany', value: 'germany' },
      { label: 'Ghana', value: 'ghana' },
      { label: 'Greece', value: 'greece' },
      { label: 'Grenada', value: 'grenada' },
      { label: 'Guatemala', value: 'guatemala' },
      { label: 'Guinea', value: 'guinea' },
      { label: 'Guinea-Bissau', value: 'guinea_bissau' },
      { label: 'Guyana', value: 'guyana' },
      { label: 'Haiti', value: 'haiti' },
      { label: 'Honduras', value: 'honduras' },
      { label: 'Hungary', value: 'hungary' },
      { label: 'Iceland', value: 'iceland' },
      { label: 'India', value: 'india' },
      { label: 'Indonesia', value: 'indonesia' },
      { label: 'Iran', value: 'iran' },
      { label: 'Iraq', value: 'iraq' },
      { label: 'Ireland', value: 'ireland' },
      { label: 'Israel', value: 'israel' },
      { label: 'Italy', value: 'italy' },
      { label: 'Jamaica', value: 'jamaica' },
      { label: 'Japan', value: 'japan' },
      { label: 'Jordan', value: 'jordan' },
      { label: 'Kazakhstan', value: 'kazakhstan' },
      { label: 'Kenya', value: 'kenya' },
      { label: 'Kiribati', value: 'kiribati' },
      { label: 'Kuwait', value: 'kuwait' },
      { label: 'Kyrgyzstan', value: 'kyrgyzstan' },
      { label: 'Laos', value: 'laos' },
      { label: 'Latvia', value: 'latvia' },
      { label: 'Lebanon', value: 'lebanon' },
      { label: 'Lesotho', value: 'lesotho' },
      { label: 'Liberia', value: 'liberia' },
      { label: 'Libya', value: 'libya' },
      { label: 'Liechtenstein', value: 'liechtenstein' },
      { label: 'Lithuania', value: 'lithuania' },
      { label: 'Luxembourg', value: 'luxembourg' },
      { label: 'Madagascar', value: 'madagascar' },
      { label: 'Malawi', value: 'malawi' },
      { label: 'Malaysia', value: 'malaysia' },
      { label: 'Maldives', value: 'maldives' },
      { label: 'Mali', value: 'mali' },
      { label: 'Malta', value: 'malta' },
      { label: 'Marshall Islands', value: 'marshall_islands' },
      { label: 'Mauritania', value: 'mauritania' },
      { label: 'Mauritius', value: 'mauritius' },
      { label: 'Mexico', value: 'mexico' },
      { label: 'Micronesia', value: 'micronesia' },
      { label: 'Moldova', value: 'moldova' },
      { label: 'Monaco', value: 'monaco' },
      { label: 'Mongolia', value: 'mongolia' },
      { label: 'Montenegro', value: 'montenegro' },
      { label: 'Morocco', value: 'morocco' },
      { label: 'Mozambique', value: 'mozambique' },
      { label: 'Myanmar (Burma)', value: 'myanmar' },
      { label: 'Namibia', value: 'namibia' },
      { label: 'Nauru', value: 'nauru' },
      { label: 'Nepal', value: 'nepal' },
      { label: 'Netherlands', value: 'netherlands' },
      { label: 'New Zealand', value: 'new_zealand' },
      { label: 'Nicaragua', value: 'nicaragua' },
      { label: 'Niger', value: 'niger' },
      { label: 'Nigeria', value: 'nigeria' },
      { label: 'North Korea', value: 'north_korea' },
      { label: 'North Macedonia', value: 'north_macedonia' },
      { label: 'Norway', value: 'norway' },
      { label: 'Oman', value: 'oman' },
      { label: 'Pakistan', value: 'pakistan' },
      { label: 'Palau', value: 'palau' },
      { label: 'Palestine', value: 'palestine' },
      { label: 'Panama', value: 'panama' },
      { label: 'Papua New Guinea', value: 'papua_new_guinea' },
      { label: 'Paraguay', value: 'paraguay' },
      { label: 'Peru', value: 'peru' },
      { label: 'Philippines', value: 'philippines' },
      { label: 'Poland', value: 'poland' },
      { label: 'Portugal', value: 'portugal' },
      { label: 'Qatar', value: 'qatar' },
      { label: 'Romania', value: 'romania' },
      { label: 'Russia', value: 'russia' },
      { label: 'Rwanda', value: 'rwanda' },
      { label: 'Saint Kitts and Nevis', value: 'saint_kitts_and_nevis' },
      { label: 'Saint Lucia', value: 'saint_lucia' },
      { label: 'Samoa', value: 'samoa' },
      { label: 'San Marino', value: 'san_marino' },
      { label: 'Saudi Arabia', value: 'saudi_arabia' },
      { label: 'Senegal', value: 'senegal' },
      { label: 'Serbia', value: 'serbia' },
      { label: 'Seychelles', value: 'seychelles' },
      { label: 'Sierra Leone', value: 'sierra_leone' },
      { label: 'Singapore', value: 'singapore' },
      { label: 'Slovakia', value: 'slovakia' },
      { label: 'Slovenia', value: 'slovenia' },
      { label: 'Solomon Islands', value: 'solomon_islands' },
      { label: 'Somalia', value: 'somalia' },
      { label: 'South Africa', value: 'south_africa' },
      { label: 'South Korea', value: 'south_korea' },
      { label: 'South Sudan', value: 'south_sudan' },
      { label: 'Spain', value: 'spain' },
      { label: 'Sri Lanka', value: 'sri_lanka' },
      { label: 'Sudan', value: 'sudan' },
      { label: 'Suriname', value: 'suriname' },
      { label: 'Sweden', value: 'sweden' },
      { label: 'Switzerland', value: 'switzerland' },
      { label: 'Syria', value: 'syria' },
      { label: 'Tajikistan', value: 'tajikistan' },
      { label: 'Tanzania', value: 'tanzania' },
      { label: 'Thailand', value: 'thailand' },
      { label: 'Timor-Leste', value: 'timor_leste' },
      { label: 'Togo', value: 'togo' },
      { label: 'Tonga', value: 'tonga' },
      { label: 'Trinidad and Tobago', value: 'trinidad_and_tobago' },
      { label: 'Tunisia', value: 'tunisia' },
      { label: 'Turkey', value: 'turkey' },
      { label: 'Turkmenistan', value: 'turkmenistan' },
      { label: 'Tuvalu', value: 'tuvalu' },
      { label: 'Uganda', value: 'uganda' },
      { label: 'Ukraine', value: 'ukraine' },
      { label: 'United Arab Emirates', value: 'uae' },
      { label: 'United Kingdom', value: 'uk' },
      { label: 'United States', value: 'usa' },
      { label: 'Uruguay', value: 'uruguay' },
      { label: 'Uzbekistan', value: 'uzbekistan' },
      { label: 'Vanuatu', value: 'vanuatu' },
      { label: 'Vatican City', value: 'vatican_city' },
      { label: 'Venezuela', value: 'venezuela' },
      { label: 'Vietnam', value: 'vietnam' },
      { label: 'Yemen', value: 'yemen' },
      { label: 'Zambia', value: 'zambia' },
      { label: 'Zimbabwe', value: 'zimbabwe' },
];

export const languages = [
      { label: 'English', value: 'english' },
      { label: 'Mandarin Chinese', value: 'mandarin' },
      { label: 'Hindi', value: 'hindi' },
      { label: 'Spanish', value: 'spanish' },
      { label: 'French', value: 'french' },
      { label: 'Arabic', value: 'arabic' },
      { label: 'Bengali', value: 'bengali' },
      { label: 'Portuguese', value: 'portuguese' },
      { label: 'Russian', value: 'russian' },
      { label: 'Japanese', value: 'japanese' },
      { label: 'German', value: 'german' },
      { label: 'Punjabi', value: 'punjabi' },
      { label: 'Javanese', value: 'javanese' },
      { label: 'Korean', value: 'korean' },
      { label: 'Vietnamese', value: 'vietnamese' },
      { label: 'Telugu', value: 'telugu' },
      { label: 'Turkish', value: 'turkish' },
      { label: 'Tamil', value: 'tamil' },
      { label: 'Italian', value: 'italian' },
      { label: 'Urdu', value: 'urdu' },
];

export const mentors = [
      {
            id: 1,
            name: 'Dianne Russell',
            role: 'Product Designer',
            experience: '08 Years Experience',
            rating: 4.8,
            startingPrice: '30$',
            topRated: true,
            image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=300&h=300',
      },
      {
            id: 2,
            name: 'James Cooper',
            role: 'UX Designer',
            experience: '06 Years Experience',
            rating: 4.9,
            startingPrice: '25$',
            topRated: false,

            image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=300&h=300',
      },
      {
            id: 3,
            name: 'Sarah Chen',
            role: 'UI Designer',
            experience: '05 Years Experience',
            rating: 4.7,
            startingPrice: '28$',
            topRated: false,
            image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=300&h=300',
      },
      {
            id: 4,
            name: 'Michael Davis',
            role: 'Product Designer',
            experience: '10 Years Experience',
            rating: 5.0,
            startingPrice: '35$',
            topRated: true,
            image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=300&h=300',
      },
      {
            id: 5,
            name: 'Olivia Martin',
            role: 'UX Designer',
            experience: '08 Years Experience',
            rating: 4.8,
            startingPrice: '28$',
            topRated: false,
            image: 'https://images.unsplash.com/photo-1525130413817-d45c1d127c42?auto=format&fit=crop&q=80&w=300&h=300',
      },
      {
            id: 6,
            name: 'Lily Brown',
            role: 'UI Designer',
            experience: '06 Years Experience',
            rating: 4.7,
            startingPrice: '25$',
            topRated: false,
            image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=300&h=300',
      },
      {
            id: 7,
            name: 'Ethan Lee',
            role: 'Product Designer',
            experience: '09 Years Experience',
            rating: 4.9,
            startingPrice: '32$',
            topRated: true,
            image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=300&h=300',
      },
      {
            id: 8,
            name: 'Samantha Smith',
            role: 'UX Designer',
            experience: '07 Years Experience',
            rating: 4.8,
            startingPrice: '30$',
            topRated: false,
            image: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=300&h=300',
      },
      {
            id: 9,
            name: 'Alexander Johnson',
            role: 'UI Designer',
            experience: '05 Years Experience',
            rating: 4.7,
            startingPrice: '28$',
            topRated: false,
            image: 'https://images.unsplash.com/photo-1525130413817-d45c1d127c42?auto=format&fit=crop&q=80&w=300&h=300',
      },
];
export const socials = [
      {
            id: 1,
            name: 'Facebook',
            icon: <BsFacebook />,
            link: '',
      },
      {
            id: 2,
            name: 'Twitter',
            icon: <BsTwitter />,
            link: '',
      },
      {
            id: 3,
            name: 'Linkedin',
            icon: <BsLinkedin />,
            link: '',
      },
      {
            id: 4,
            name: 'Instagram',
            icon: <BsInstagram />,
            link: '',
      },
      // {
      //       id: 5,
      //       name: 'Youtube',
      //       icon: <BsYoutube />,
      //       link: '',
      // },
];
