export const timeZones = [
      { value: 'GMT-12:00', label: '(GMT -12:00) International Date Line West' },
      { value: 'GMT-11:00', label: '(GMT -11:00) Midway Island, Samoa' },
      { value: 'GMT-10:00', label: '(GMT -10:00) Hawaii' },
      { value: 'GMT-09:00', label: '(GMT -09:00) Alaska' },
      { value: 'GMT-08:00', label: '(GMT -08:00) Pacific Time (US & Canada)' },
      { value: 'GMT-07:00', label: '(GMT -07:00) Mountain Time (US & Canada)' },
      { value: 'GMT-06:00', label: '(GMT -06:00) Central Time (US & Canada), Mexico City' },
      { value: 'GMT-05:00', label: '(GMT -05:00) Eastern Time (US & Canada), Bogota, Lima' },
      { value: 'GMT-04:00', label: '(GMT -04:00) Atlantic Time (Canada), Caracas, La Paz' },
      { value: 'GMT-03:30', label: '(GMT -03:30) Newfoundland' },
      { value: 'GMT-03:00', label: '(GMT -03:00) Brazil, Buenos Aires, Georgetown' },
      { value: 'GMT-02:00', label: '(GMT -02:00) Mid-Atlantic' },
      { value: 'GMT-01:00', label: '(GMT -01:00) Azores, Cape Verde Islands' },
      { value: 'GMT+00:00', label: '(GMT +00:00) Western Europe Time, London, Lisbon, Casablanca' },
      { value: 'GMT+01:00', label: '(GMT +01:00) Central Europe Time, Brussels, Copenhagen, Madrid, Paris' },
      { value: 'GMT+02:00', label: '(GMT +02:00) Eastern Europe Time, Cairo, Athens, Jerusalem' },
      { value: 'GMT+03:00', label: '(GMT +03:00) Baghdad, Riyadh, Moscow, St. Petersburg' },
      { value: 'GMT+03:30', label: '(GMT +03:30) Tehran' },
      { value: 'GMT+04:00', label: '(GMT +04:00) Abu Dhabi, Muscat, Baku, Tbilisi' },
      { value: 'GMT+04:30', label: '(GMT +04:30) Kabul' },
      { value: 'GMT+05:00', label: '(GMT +05:00) Islamabad, Karachi, Tashkent' },
      { value: 'GMT+05:30', label: '(GMT +05:30) Chennai, Kolkata, Mumbai, New Delhi' },
      { value: 'GMT+05:45', label: '(GMT +05:45) Kathmandu' },
      { value: 'GMT+06:00', label: '(GMT +06:00) Astana, Dhaka' },
      { value: 'GMT+06:30', label: '(GMT +06:30) Yangon (Rangoon)' },
      { value: 'GMT+07:00', label: '(GMT +07:00) Bangkok, Hanoi, Jakarta' },
      { value: 'GMT+08:00', label: '(GMT +08:00) Beijing, Perth, Singapore, Hong Kong' },
      { value: 'GMT+09:00', label: '(GMT +09:00) Tokyo, Seoul, Osaka, Sapporo, Yakutsk' },
      { value: 'GMT+09:30', label: '(GMT +09:30) Adelaide, Darwin' },
      { value: 'GMT+10:00', label: '(GMT +10:00) Eastern Australia, Guam, Vladivostok' },
      { value: 'GMT+11:00', label: '(GMT +11:00) Magadan, Solomon Islands, New Caledonia' },
      { value: 'GMT+12:00', label: '(GMT +12:00) Auckland, Wellington, Fiji, Kamchatka' },
      { value: 'GMT+13:00', label: "(GMT +13:00) Nuku'alofa" },
];
